# Generated by Django 5.2.7 on 2025-10-24 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('size_in_hectares', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('telephone', models.CharField(blank=True, max_length=100)),
                ('account_number', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('sector', models.CharField(choices=[('Agro', 'Agro'), ('General Agriculture', 'General Agriculture'), ('Horticulture', 'Horticulture'), ('Kapenta', 'Kapenta'), ('Timber', 'Timber'), ('Tea & Coffee', 'Tea & Coffee'), ('Sugarcane', 'Sugarcane')], max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_notices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=20)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_visits', to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='farm.farm')),
            ],
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='farm.farm')),
            ],
        ),
        migrations.CreateModel(
            name='FarmEmployeeStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporting_month', models.DateField(help_text='The month this record applies to')),
                ('employment_type', models.CharField(choices=[('PERMANENT', 'Permanent'), ('SEASONAL', 'Seasonal'), ('CASUAL', 'Casual'), ('FIXED_TERM', 'Fixed Term')], max_length=20)),
                ('citizen_male', models.PositiveIntegerField(default=0)),
                ('citizen_female', models.PositiveIntegerField(default=0)),
                ('expatriate_male', models.PositiveIntegerField(default=0)),
                ('expatriate_female', models.PositiveIntegerField(default=0)),
                ('basic_pay_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('basic_pay_zwl', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('employees_contribution_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('employees_contribution_zwl', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('employers_contribution_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('employers_contribution_zwl', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('arrears_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('arrears_zwl', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_contribution_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_contribution_zwl', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_employee_stats', to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_stats', to='farm.farm')),
            ],
            options={
                'verbose_name_plural': 'Farm Employee Stats',
                'unique_together': {('farm', 'reporting_month', 'employment_type')},
            },
        ),
    ]
