# Generated by Django 5.2.7 on 2025-10-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('ZWL', 'ZWL')], default='USD', max_length=10),
        ),
    ]
