# Generated by Django 5.2.7 on 2025-10-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_statement_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitevisit',
            name='purpose',
            field=models.CharField(default='General Inspection', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitevisit',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='PENDING', max_length=20),
        ),
    ]
